/************************
1. SELECT
*************************/

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE LASTNAME = 'King';

SELECT * FROM EMPLOYEE
WHERE FIRSTNAME = 'Andrew'
AND REPORTSTO IS NULL;

/*********************
2.ORDER BY
**********************/

SELECT FIRSTNAME FROM CUSTOMER
ORDER BY CITY ASC;

SELECT * FROM ALBUM
ORDER BY TITLE DESC;

/*********************
3.INSERT
**********************/

INSERT INTO GENRE
VALUES (26, 'A capella');

INSERT INTO GENRE
VALUES (27, 'Country');

INSERT INTO EMPLOYEE
VALUES (9,'Doe','John','IT Staff',6,TO_DATE('28-FEB-85','DD-MON-YY'),TO_DATE('01-JAN-00','DD-MON-YY'),'123 Main Street','Calgary','AB','Canada','T3B 0C5', '+1 (403) 867-5309', '+1 (403) 567-5311','john@chinookcorp.com');

INSERT INTO EMPLOYEE
VALUES (10,'Sherman','Philip','IT Staff',6,TO_DATE('13-FEB-64','DD-MON-YY'),TO_DATE('01-JAN-03','DD-MON-YY'),'42 Wallaby Way','Sydney','NSW','Australia','1001', '+61 04 3456 1234', '+61 04 3456 1345','philip@chinookcorp.com');

INSERT INTO CUSTOMER
VALUES (60, 'Mike','Wozowski','Monsters, Inc.', '1 Main St','New York','NY','USA', '10153','+1 (202) 867-5309', NULL, 'wozowski@scare.com',3);

INSERT INTO CUSTOMER
VALUES (61, 'James','Sullivan','Monsters, Inc.', '1 Main St','New York','NY','USA', '10153','+1 (202) 867-5310', NULL, 'sully@scare.com',3);

/*******************
4. UPDATE
********************/

UPDATE ARTIST
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';

UPDATE CUSTOMER
SET FIRSTNAME = 'Robert', LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchell';

/*********************
5. LIKE
**********************/

SELECT * FROM INVOICE
WHERE BILLINGADDRESS LIKE 'T%';

/*********************
6. BETWEEN
**********************/

SELECT * FROM INVOICE
WHERE TOTAL > 15 AND TOTAL < 50;

SELECT * FROM EMPLOYEE
WHERE HIREDATE BETWEEN TO_DATE('01-JUN-03','DD-MON-YY') AND TO_DATE('01-MAR-04','DD-MON-YY');

/*********************
7. DELETE
**********************/

DELETE FROM
(SELECT * FROM CUSTOMER 
    INNER JOIN INVOICE 
        ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
    INNER JOIN INVOICELINE
        ON INVOICE.INVOICEID = INVOICELINE.INVOICEID
WHERE CUSTOMER.FIRSTNAME = 'Robert' AND CUSTOMER.LASTNAME = 'Walter');

/********************
8. JOINS
*********************/

SELECT C.FIRSTNAME,I.INVOICEID FROM CUSTOMER C
INNER JOIN INVOICE I
ON C.CUSTOMERID = I.CUSTOMERID;

SELECT C.CUSTOMERID,C.FIRSTNAME,C.LASTNAME,I.INVOICEID,I.TOTAL FROM CUSTOMER C
JOIN INVOICE I
ON C.CUSTOMERID = I.CUSTOMERID;

SELECT ARTIST.NAME, ALBUM.TITLE FROM ALBUM
RIGHT OUTER JOIN ARTIST
ON ALBUM.ARTISTID = ARTIST.ARTISTID;

SELECT * FROM ARTIST,ALBUM
WHERE ARTIST.ARTISTID = ALBUM.ARTISTID
ORDER BY ARTIST.NAME ASC;

SELECT * FROM EMPLOYEE E
JOIN EMPLOYEE M
ON E.REPORTSTO = M.EMPLOYEEID;

SELECT * FROM EMPLOYEE
INNER JOIN CUSTOMER
    ON EMPLOYEE.EMPLOYEEID = CUSTOMER.SUPPORTREPID
INNER JOIN INVOICE
    ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
INNER JOIN INVOICELINE
    ON INVOICE.INVOICEID = INVOICELINE.INVOICEID
INNER JOIN TRACK
    ON INVOICELINE.TRACKID = TRACK.TRACKID
INNER JOIN GENRE
    ON TRACK.GENREID = GENRE.GENREID 
INNER JOIN MEDIATYPE
    ON TRACK.MEDIATYPEID = MEDIATYPE.MEDIATYPEID
INNER JOIN ALBUM
    ON TRACK.ALBUMID = ALBUM.ALBUMID
INNER JOIN ARTIST
    ON ALBUM.ARTISTID = ARTIST.ARTISTID
INNER JOIN PLAYLISTTRACK
    ON TRACK.TRACKID = PLAYLISTTRACK.TRACKID
INNER JOIN PLAYLIST
    ON PLAYLISTTRACK.PLAYLISTID = PLAYLIST.PLAYLISTID;



